### PR TITLE
Minor cleanup to github tracker and new fancy readme.

### PR DESCRIPTION
**Pull request by MFernflower**
I did these changes in about half an hour and was wondering if you'd like them.

### CODE REVIEW

**Comment by MFernflower** [comment]
Also, when the pr is accepted or rejected - I will delete my copy of the repo as soon as I can (to avoid confusion)

**Comment by mattodd** [comment]
Forgive me for an obvious question. How do I see the before and after?

**Comment by MFernflower** [comment]
https://github.com/OpenSourceMalaria/OSM_To_Do_List/pull/359/files

**Comment by miike** [comment]
Looks good to me. We don't really need much of a .gitignore for this repo as it's used primarily to track issues but I'm happy to merge this if @mattodd is happy with the changes. :+1:

**Comment by mattodd** [comment]
OK, thanks to you both.

On 16 November 2015 at 13:35, miike <notifications@github.com> wrote:

> Looks good to me. We don't really need much of a .gitignore for this repo
> as it's used primarily to track issues but I'm happy to merge this if
> @mattodd <https://github.com/mattodd> is happy with the changes. [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/pull/359#issuecomment-156891818>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by miike** [comment]
Thanks @MFernflower, merged!

**Comment by MFernflower** [comment]
Glad to have done something that isn't theoretical :D

**Pull request merged**
